version: "3.8"

services:
  fastapi_tryout:
    container_name: fastapi_tryout
    build:
      context: .
      dockerfile: Dockerfile
    image: fastapi_tryout
    env_file:
      - .env
    volumes:
      - ./src:/src
    ports:
      - ${FASTAPI_PORT}:${FASTAPI_PORT}
    depends_on:
      - fastapi_tryout_posgres

  fastapi_tryout_posgres:
    image: postgres:13-alpine
    container_name: ${POSTGRES_HOST}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  fastapi_tryout_pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - fastapi_tryout_posgres

volumes:
  postgres_data: